name: CI

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push
        run: docker build --file ./src/BlazorRackManager/Dockerfile --tag anthonyryck/rackmanager:ci .
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --
      - name: Push to DockerHub
        run: docker push anthonyryck/rackmanager:ci
